version: '3.7'
services:
  db:
    image: postgres:alpine
    env_file: .env

  backend:
    build: ./backend
    depends_on:
      - db
    volumes:
       - ./backend:/app
    entrypoint: /development.sh
    env_file: .env

  frontend:
    image: node:alpine
    volumes:
       - ./frontend:/app
    working_dir: /app
    command: npm run serve
    depends_on:
      - backend
  
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    depends_on:
      - backend
    volumes:
      - ./backend/static_content/media/:/media/
      - ./backend/static_content/static/:/static/
      - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro
